### ISSUE TITLE
Does the POJO mapping mechanism provide support for Enums?

### ISSUE THREAD

**Issue by jjzazuet** [yeagy/bss#2]
Hi. Nice library!

Just like the title says, can we have auto mapping support for objects that define `Enum` class members? Thanks!

**Comment by yeagy** [comment]
It does as of 0.5.1. Thanks for pointing that out!

**Comment by yeagy** [comment]
It will take a few hours for the new version to become visible in maven central, but I uploaded it to the releases tab if you can't wait!

**Comment by jjzazuet** [comment]
@yeagy I'll give a shot for sure. Thanks!
